# Generated by Django 5.2.7 on 2025-11-24 03:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Socio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre_completo', models.CharField(max_length=150)),
                ('documento', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=30, null=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('suspendido', 'Suspendido')], default='activo', max_length=15)),
                ('datos_fiscales', models.JSONField(blank=True, default=dict)),
                ('fecha_alta', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(blank=True, db_column='usuario_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='socio', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Socio',
                'verbose_name_plural': 'Socios',
                'db_table': 'socio',
            },
        ),
        migrations.CreateModel(
            name='SocioAuditLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('actualizacion', 'Actualizacion'), ('cambio_estado', 'Cambio de estado')], max_length=32)),
                ('estado_anterior', models.CharField(blank=True, choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('suspendido', 'Suspendido')], max_length=15)),
                ('estado_nuevo', models.CharField(blank=True, choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('suspendido', 'Suspendido')], max_length=15)),
                ('campos_modificados', models.JSONField(blank=True, default=list)),
                ('datos_previos', models.JSONField(blank=True, default=dict)),
                ('datos_nuevos', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='socios_modificados', to=settings.AUTH_USER_MODEL)),
                ('socio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auditorias', to='socios.socio')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
