# Generated by Django 5.2.7 on 2025-11-10 02:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='socio',
            name='datos_fiscales',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='socio',
            name='estado',
            field=models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('suspendido', 'Suspendido')], default='activo', max_length=15),
        ),
        migrations.CreateModel(
            name='SocioAuditLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('actualizacion', 'Actualizacion'), ('cambio_estado', 'Cambio de estado')], max_length=32)),
                ('estado_anterior', models.CharField(blank=True, choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('suspendido', 'Suspendido')], max_length=15)),
                ('estado_nuevo', models.CharField(blank=True, choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('suspendido', 'Suspendido')], max_length=15)),
                ('campos_modificados', models.JSONField(blank=True, default=list)),
                ('datos_previos', models.JSONField(blank=True, default=dict)),
                ('datos_nuevos', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='socios_modificados', to=settings.AUTH_USER_MODEL)),
                ('socio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auditorias', to='socios.socio')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
