# Generated by Django 5.2.7 on 2025-12-01 16:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=14)),
                ('tasa_interes', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('moroso', 'Moroso'), ('pagado', 'Pagado'), ('cancelado', 'Cancelado')], default='activo', max_length=15)),
                ('fecha_desembolso', models.DateField()),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('socio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestamos', to='socios.socio')),
            ],
            options={
                'db_table': 'prestamo',
                'ordering': ['-fecha_desembolso', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=14)),
                ('fecha_pago', models.DateField()),
                ('metodo', models.CharField(blank=True, max_length=50)),
                ('referencia', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('prestamo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='socios.prestamo')),
            ],
            options={
                'db_table': 'pago',
                'ordering': ['-fecha_pago', '-created_at'],
            },
        ),
    ]
