# Generated by Django 5.2.7 on 2025-12-02 04:51

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0002_prestamo_pago'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoPrestamo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=80, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('tasa_interes_anual', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('plazo_meses', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('requisitos', models.JSONField(blank=True, default=list)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tipo de prestamo',
                'verbose_name_plural': 'Tipos de prestamo',
                'db_table': 'tipo_prestamo',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='prestamo',
            name='tipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prestamos', to='socios.tipoprestamo'),
        ),
    ]
