# Generated by Django 5.2.7 on 2025-12-05 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="""
                    ALTER TABLE usuario
                    ADD COLUMN IF NOT EXISTS email_verificado boolean NOT NULL DEFAULT false;
                    """,
                    reverse_sql="""
                    ALTER TABLE usuario
                    DROP COLUMN IF EXISTS email_verificado;
                    """
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='usuario',
                    name='email_verificado',
                    field=models.BooleanField(default=False),
                ),
            ],
        ),
    ]
